### ISSUE TITLE
[Crash] - Incompatible with Create (Fabric)

### ISSUE THREAD

**Issue by havi05** [Wartori54/ImmersivePortalsSurvivalAdaptation#5]
Problem:
I can't use Immersive Portals Survival together with create (Fabric). Immersive Portals (not survival) and create are working together.
I hope you can help me fixing this.

https://user-images.githubusercontent.com/71942164/166663801-629e70f4-6ef7-4bd1-a20e-f46a9b8a00fa.mp4

Minecraft Version: 1.18.1 (Fabric)
Mods: 
- Create (Fabric) v0.4d+482 (https://github.com/Fabricators-of-Create/Create)
- immersive portals 1.2.5
- immersive portals survival 0.7.0
- fabric api 0.46.6    

Log:

````
12:14:06.969 PLAYERNAME joined the game
12:14:06.972 [Nbt Crafting] Syncing advanced recipe data to player _Estragon_
12:14:07.018 Received Dimension Type Sync
12:14:07.018 
immersive_portals:alternate5 -> immersive_portals:surface_type
immersive_portals:alternate4 -> immersive_portals:surface_type
minecraft:the_end -> minecraft:the_end
minecraft:overworld -> minecraft:overworld
immersive_portals:alternate1 -> immersive_portals:surface_type
minecraft:the_nether -> minecraft:the_nether
immersive_portals:alternate3 -> immersive_portals:surface_type
immersive_portals:alternate2 -> immersive_portals:surface_type
12:14:07.018 Received Dimension Int Id Sync
12:14:07.018 
minecraft:overworld -> 0
immersive_portals:alternate1 -> 2
immersive_portals:alternate2 -> 3
minecraft:the_nether -> -1
immersive_portals:alternate3 -> 4
immersive_portals:alternate4 -> 5
minecraft:the_end -> 1
immersive_portals:alternate5 -> 6

12:14:07.053 WorldRenderer reloaded minecraft:overworld
12:14:07.075 Encountered exception while handling in channel with name "nbtcrafting:update_advanced_recipes"
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:136)
	at net.minecraft.class_2507.method_10625(class_2507.java:75)
	at net.minecraft.class_2540.method_30616(class_2540.java:450)
	at net.minecraft.class_2540.method_10798(class_2540.java:432)
	at de.siphalor.nbtcrafting.ingredient.IngredientEntryCondition.read(IngredientEntryCondition.java:97)
	at de.siphalor.nbtcrafting.ingredient.IngredientMultiStackEntry.read(IngredientMultiStackEntry.java:94)
	at net.minecraft.class_1856.handler$bfi000$fromPacket(class_1856.java:1687)
	at net.minecraft.class_1856.method_8086(class_1856.java)
	at net.minecraft.class_1867$class_1868.method_8141(class_1867.java:113)
	at net.minecraft.class_1867$class_1868.method_8122(class_1867.java:79)
	at de.siphalor.nbtcrafting.client.NbtCraftingClient.lambda$onInitializeClient$3(NbtCraftingClient.java:68)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89)
	at net.minecraft.class_634.handler$zji000$handleCustomPayload(class_634.java:2429)
	at net.minecraft.class_634.method_11152(class_634.java)
	at net.minecraft.class_2658.method_11457(class_2658.java:60)
	at net.minecraft.class_2658.method_11054(class_2658.java:8)
	at net.minecraft.class_2535.method_10759(class_2535.java:163)
	at net.minecraft.class_2535.method_10770(class_2535.java:150)
	at net.minecraft.class_2535.channelRead0(class_2535.java:53)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:852)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
	at io.netty.channel.local.LocalChannel.access$000(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$1.run(LocalChannel.java:68)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException
	at io.netty.buffer.ByteBufInputStream.readByte(ByteBufInputStream.java:212)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:33)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2507.method_10626(class_2507.java:131)
	... 88 more
12:14:07.078 PLAYERNAME lost connection: Disconnected
12:14:07.079 PLAYERNAME left the game
12:14:07.084 Stopping singleplayer server as player logged out
12:14:07.101 Stopping server

````

**Comment by Wartori54** [comment]
Hey, thank you so much for the detailed description of your crash, but unfortunately create for fabric is still in very early development versions.
If I would get a fix for this version specific version of create, in 15 days another crash would occur. This would make an infinite loop of finding a crash and patching it that would waste a lot of effort.
Finally the crash is (i think by the looks of the crash report) not my fault, its nbtcrafting's fault (a library that i use). So you probably should try with create and nbtcrafting alone (nbtcrafting is in curseforge), and if it crashes then make a bug report to them.
I'm very sorry for not being able to help, but as I said create is too early in development to give them support (at least for me).
Bye :)

**Comment by havi05** [comment]
Thank you very much for the explanation.

**Comment by Kat-09** [comment]
> Hey, thank you so much for the detailed description of your crash, but unfortunately create for fabric is still in very early development versions. If I would get a fix for this version specific version of create, in 15 days another crash would occur. This would make an infinite loop of finding a crash and patching it that would waste a lot of effort. Finally the crash is (i think by the looks of the crash report) not my fault, its nbtcrafting's fault (a library that i use). So you probably should try with create and nbtcrafting alone (nbtcrafting is in curseforge), and if it crashes then make a bug report to them. I'm very sorry for not being able to help, but as I said create is too early in development to give them support (at least for me). Bye :)

Hey umm Btw do you think it's too early now cuz like They have released it on curseforge so it might be stable enough idk lol thank you either way :D :D

**Comment by Wartori54** [comment]
Ok, i'll look at that

**Comment by Wartori54** [comment]
This didn't really happen and I don't think its going to happen soon either, see [this](https://github.com/Wartori54/ImmersivePortalsSurvivalAdaptation/issues/7#issuecomment-2758903693) for more info.
