### ISSUE TITLE
[Crash] - Starting Minecraft 1.18.2

### ISSUE THREAD

**Issue by havi05** [Wartori54/ImmersivePortalsSurvivalAdaptation#6]
When I load this mod in Minecraft 1.18.2, it crashes immediately.
I hope you can fix the problem or help me debug it (if it's a problem with a library or something else).

Mods used:
- fabric-api-0.51.1+1.18.2
- immersive-portals-1.3.6-mc1.18.2-fabric
- Immersive-portals-surivial-adaptation-0.7.0

Log:
````
19:01:47.783 Preparing to launch minecraft client for fabric-loader-0.13.3-1.18.2
19:01:50.361 Minecraft client fabric-loader-0.13.3-1.18.2 is ready to start.
19:01:50.362 Starting!
19:01:50.544 Using default game log configuration client-1.12.xml (outputs XML)
19:01:51.374 Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
19:01:51.645 Loading 57 mods:
	- blue_endless_jankson 1.2.1 via jankson
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via immersive_portals
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.13.3
	- imm_ptl_core 1.3.6 via immersive_portals
	- imm_ptl_surv_adapt 0.7.0
	- immersive_portals 1.3.6
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- libgui 5.1.0+1.18 via imm_ptl_surv_adapt
	- libninepatch 1.1.0 via libgui
	- minecraft 1.18.2
	- nbtcrafting 2.1.0+mc1.18-pre1 via imm_ptl_surv_adapt
	- q_misc_util 1.3.6 via immersive_portals
19:01:51.872 SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Victor/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
19:01:51.986 Compatibility level set to JAVA_16
19:01:52.062 Compatibility level set to JAVA_17
19:01:57.217 Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/tool/attribute/v1/FabricToolTags
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/tool/attribute/v1/FabricToolTags
	at net.wartori.imm_ptl_surv_adapt.Blocks.PortalBlock.<init>(PortalBlock.java:12)
	at net.wartori.imm_ptl_surv_adapt.Register.<clinit>(Register.java:69)
	at net.minecraft.class_3864.handler$zmp000$addDefaultOres(class_3864.java:535)
	at net.minecraft.class_3864.method_17006(class_3864.java:75)
	at net.minecraft.class_3864.method_38568(class_3864.java:48)
	at net.minecraft.class_5478.method_30701(class_5478.java:226)
	at net.minecraft.class_5504.<clinit>(class_5504.java:12)
	at net.minecraft.class_5458.method_30566(class_5458.java:86)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:85)
	at net.minecraft.class_2378.<clinit>(class_2378.java:291)
	at net.minecraft.class_2966.method_12851(class_2966.java:49)
	at net.minecraft.client.main.Main.main(Main.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
19:01:57.974 
19:01:57.974 Process crashed with exit code 1
````

**Comment by Wartori54** [comment]
Version 0.7.0 is only compatible with 1.18 and 1.18.1. A new version is in the works to update to 1.18.2 and re add the structure
